import type { Character } from "@prisma/client";
import { Prisma } from "@prisma/client";
export interface TurnLog {
    turn: number;
    attacker: "Player" | "Enemy";
    damage: number;
    message: string;
}
/**
 * 📊 RADIAL DEPTH TIERS & REWARDS
 */
export declare const getDepthTier: (depth: number) => {
    name: string;
    dangerMult: number;
    expMult: number;
    lootMult: number;
    prefix: string;
};
export declare function generatePVEEncounter(character: Character): Promise<{
    type: string;
    name: string;
    hp: number;
    maxHp: number;
    attack: number;
    defense: number;
    expValue: number;
}>;
export declare function generateGatheringEncounter(character: Character): Promise<{
    type: string;
    name: string;
    icon: string;
    amount: number;
    hp: number;
    maxHp: number;
    xpReward: number;
    itemCode: string;
}>;
export declare function executeCombat(character: Character, enemy: any): Promise<{
    success: boolean;
    isWin: boolean;
    updatedChar: {
        int: number;
        name: string;
        id: string;
        hp: number;
        createdAt: Date;
        updatedAt: Date;
        level: number;
        exp: number;
        maxHp: number;
        currentDepth: number;
        actionStatus: string;
        lastPulseAt: Date | null;
        previousStatus: string | null;
        pendingEncounter: Prisma.JsonValue | null;
        currentPath: Prisma.JsonValue | null;
        dungeonProgress: number | null;
        dungeonData: Prisma.JsonValue | null;
        str: number;
        agi: number;
        dex: number;
        luk: number;
        statPoints: number;
        gold: number;
        energy: number;
        maxEnergy: number;
        userId: string;
        equippedWeaponId: string | null;
        equippedChestId: string | null;
        equippedHelmetId: string | null;
        equippedBootsId: string | null;
    };
    log: {
        id: string;
        createdAt: Date;
        characterId: string;
        enemyName: string;
        logDetails: Prisma.JsonValue;
        isWin: boolean;
        expGained: number;
    };
    loot: any[];
}>;
export declare function executeGathering(character: Character, node: any): Promise<{
    success: boolean;
    type: string;
    item: any;
    amount: any;
    updatedChar: {
        int: number;
        name: string;
        id: string;
        hp: number;
        createdAt: Date;
        updatedAt: Date;
        level: number;
        exp: number;
        maxHp: number;
        currentDepth: number;
        actionStatus: string;
        lastPulseAt: Date | null;
        previousStatus: string | null;
        pendingEncounter: Prisma.JsonValue | null;
        currentPath: Prisma.JsonValue | null;
        dungeonProgress: number | null;
        dungeonData: Prisma.JsonValue | null;
        str: number;
        agi: number;
        dex: number;
        luk: number;
        statPoints: number;
        gold: number;
        energy: number;
        maxEnergy: number;
        userId: string;
        equippedWeaponId: string | null;
        equippedChestId: string | null;
        equippedHelmetId: string | null;
        equippedBootsId: string | null;
    };
    log: {
        id: string;
        createdAt: Date;
        characterId: string;
        enemyName: string;
        logDetails: Prisma.JsonValue;
        isWin: boolean;
        expGained: number;
    };
    startIntegrity: any;
}>;
export declare function processPVP(character: Character): Promise<{
    success: boolean;
    type: string;
    isWin: boolean;
    updatedChar: {
        int: number;
        name: string;
        id: string;
        hp: number;
        createdAt: Date;
        updatedAt: Date;
        level: number;
        exp: number;
        maxHp: number;
        currentDepth: number;
        actionStatus: string;
        lastPulseAt: Date | null;
        previousStatus: string | null;
        pendingEncounter: Prisma.JsonValue | null;
        currentPath: Prisma.JsonValue | null;
        dungeonProgress: number | null;
        dungeonData: Prisma.JsonValue | null;
        str: number;
        agi: number;
        dex: number;
        luk: number;
        statPoints: number;
        gold: number;
        energy: number;
        maxEnergy: number;
        userId: string;
        equippedWeaponId: string | null;
        equippedChestId: string | null;
        equippedHelmetId: string | null;
        equippedBootsId: string | null;
    };
    log: {
        id: string;
        createdAt: Date;
        characterId: string;
        enemyName: string;
        logDetails: Prisma.JsonValue;
        isWin: boolean;
        expGained: number;
    };
}>;
export declare function processDungeonEncounter(character: Character): Promise<{
    success: boolean;
    isWin: boolean;
    updatedChar: {
        int: number;
        name: string;
        id: string;
        hp: number;
        createdAt: Date;
        updatedAt: Date;
        level: number;
        exp: number;
        maxHp: number;
        currentDepth: number;
        actionStatus: string;
        lastPulseAt: Date | null;
        previousStatus: string | null;
        pendingEncounter: Prisma.JsonValue | null;
        currentPath: Prisma.JsonValue | null;
        dungeonProgress: number | null;
        dungeonData: Prisma.JsonValue | null;
        str: number;
        agi: number;
        dex: number;
        luk: number;
        statPoints: number;
        gold: number;
        energy: number;
        maxEnergy: number;
        userId: string;
        equippedWeaponId: string | null;
        equippedChestId: string | null;
        equippedHelmetId: string | null;
        equippedBootsId: string | null;
    };
    log: {
        id: string;
        createdAt: Date;
        characterId: string;
        enemyName: string;
        logDetails: Prisma.JsonValue;
        isWin: boolean;
        expGained: number;
    };
    loot: any[];
}>;
//# sourceMappingURL=combatEngine.d.ts.map